@api = http://localhost:3000/task

GET {{api}}
###
GET {{api}}/10
###
GET {{api}}/count

###
PUT {{api}}/10
Content-Type: application/json

{
    "title": "ya no es una tarea"
}
###
POST {{api}}
Content-Type:application/json

{
    "title": "task 3",
    "description": "guardar en git"
}

### 
DELETE {{api}}/100
